# us-central1-docker.pkg.dev/intrinsic-research-431300/intrinsic-research/intrinsic-finbert:v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
spec:
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        - name: ml-model
          image: us-central1-docker.pkg.dev/intrinsic-research-431300/intrinsic-research/intrinsic-finbert:v1
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "2"
